version: "3.7"

services:
  flask:
    build: .
    working_dir: /data/www
    # command: sh -c "gunicorn --bind=flask:3000 --workers=4 app:app" #production
    command: sh -c "gunicorn --bind=flask:3000 --workers=1 app:app --reload && ln -sf /dev/stdout mylog.log && ln -sf /dev/stderr mylog.log "
    # command: sh -c "ls"
    environment:
      FLASK_APP: app.py
      FLASK_DEBUG: 1 
      FLASK_RUN_HOST: 0.0.0.0
      POSTGRES_DB: cansat
    ports:
      - 3000:3000
      - 5000:5000
    volumes:
      - ./:/data/www
      - /data/www/temp
    restart: always
    depends_on:
      - PostGIS
  nginx:
    image: nginx:alpine
    command: [nginx, '-g', 'daemon off;']
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx
      - ./:/data/www
    restart: always
    depends_on:
      - flask
  PostGIS:
    image: postgis/postgis:12-3.0-alpine
    #command: cat /etc/passwd
    environment: 
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: cansat
      POSTGRES_DB: cansat
    ports: 
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    # - /etc/passwd:/etc/passwd:ro #read only, to have the same permisions as host user (trying to fix permisions..)
    #user: "1000:1000"
    restart: always
